<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "common_email_templates" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link https://www.mailwizz.com/
 * @copyright 2013-2018 MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'View email templates' => 'View email templates',
  'Common email templates' => 'Common email templates',
  'Template' => 'Template',
  'Name' => 'Name',
  'Slug' => 'Slug',
  'Subject' => 'Subject',
  'Content' => 'Content',
  'This will delete the core email templates and will reinstall them based on the common template. Are you sure you want to continue?' => 'This will delete the core email templates and will reinstall them based on the common template. Are you sure you want to continue?',
  'Reinstall core templates' => 'Reinstall core templates',
);
