<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "console" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'ID' => 'ID',
  'Command' => 'Command',
  'Action' => 'Action',
  'Params' => 'Params',
  'Start time' => 'Start time',
  'End time' => 'End time',
  'Start memory' => 'Start memory',
  'End memory' => 'End memory',
  'Duration' => 'Duration',
  'Memory usage' => 'Memory usage',
  'seconds' => 'seconds',
);
