<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "countries" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Please note that removing this country will also remove every record that depends on it, such as zones, taxes, customer companies, etc!' => 'Обратите внимание, что удаление этой страны также удалит каждую запись, которая зависит от нее, например, зоны, налоги, компании-клиенты и т. д.!',
  'Are you still sure you want to remove this country? There is no coming back after you do it!' => 'Вы все еще уверены, что хотите удалить эту страну? Это изменение нельзя отменить!',
  'View countries' => 'Просмотр стран',
  'Countries' => 'Страны',
  'Create new country' => 'Создать новую страну',
  'Update country' => 'Обновить страну',
  'Confirm country removal' => 'Подтвердить удаление страны',
  'Country' => 'Страна',
  'Name' => 'Имя',
  'Code' => 'Код',
);
