<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "ext_bulk_email_checker" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link https://www.mailwizz.com/
 * @copyright MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Bulk Email Checker' => 'Bulk Email Checker',
  'Common' => 'Common',
  'Please note that this extension will be used globally, for absolutely each email address that is checked against the blacklist.' => 'Please note that this extension will be used globally, for absolutely each email address that is checked against the blacklist.',
  'Api key' => 'Api key',
  'The api key for BulkEmailChecker.com service' => 'The api key for BulkEmailChecker.com service',
);
