<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "ext_backup_manager" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link https://www.mailwizz.com/
 * @copyright 2013-2018 MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Backup manager' => 'Менеджер бекапов',
  'Settings' => 'Настройки',
  'Storage path' => 'Путь сохранения',
  'Auto backup' => 'Автоматический бекап',
  'Auto backup frequency' => 'Частота автоматического бекапа',
  'Keep max backups' => 'Максимальное кол-во бекапов',
  'Success notifications' => 'Уведомления об успехе',
  'Error notifications' => 'Уведомления о неудаче',
  'The path on this file system where we should store the backups. Please note that your current system user must be able to write there. Also, do not set a path inside your public html folder since doing this will backup the previously made backups!' => 'Путь где мы должны хранить резервные копии. Обратите внимание, что ваш текущий системный пользователь должен иметь возможность записи туда. Кроме того, не устанавливайте путь в вашей общедоступной html-папке, так как это сделает резервную копию ранее сделанных резервных копий!',
  'Whether the auto backup is enabled' => 'Включено ли автоматическое резервное копирование',
  'Once at how many days the auto backup process should run and create the backup' => 'Чеез сколько дней должен запуститься процесс автоматического резервного копирования и создать резервную копию',
  'The maximum number of backups the system must keep, older backups are removed to save disk space' => 'Максимальное количество резервных копий, которое должна хранить система, более старые резервные копии удаляются для экономии места на диске.',
  'A single email address, or a list of emails separated by comma, to where the system should send notifications when a backup is completed successfully' => 'Адрес электронной почты или список, разделенный запятыми, куда система должна отправлять уведомления при успешном завершении резервного копирования',
  'A single email address, or a list of emails separated by comma, to where the system should send notifications when a backup fails' => 'Адрес электронной почты или список, разделенный запятыми, куда система должна отправлять уведомления при сбое резервного копирования',
  'Backup snapshots' => 'Резервные снимки',
  'Snapshots' => 'Снимки',
  'Create new backup snapshot' => 'Создать новый бекап',
  'Snapshot' => 'Снимок',
  'Name' => 'Имя',
  'Path' => 'Путь',
  'Size' => 'Размер',
  'Meta data' => 'Метаданные',
  'Starting the backup process...' => 'Запуск процесса резервного копирования...',
  'Checking to see if the storage directory exists...' => 'Проверка, существует ли каталог хранилища...',
  'The storage directory exists.' => 'Каталог сохранения существует.',
  'The directory for this backup is: {dir}' => 'Каталог для этой резервной копии: {dir}',
  'Checking to see if the directory for this backup exists...' => 'Проверка, существует ли каталог для этой резервной копии...',
  'The backup directory does not exists, trying to create it...' => 'Каталог резервного копирования не существует, пытается создать его...',
  'Unable to create the directory, please check the permissions!' => 'Невозможно создать каталог, пожалуйста, проверьте разрешения!',
  'The backup directory has been created.' => 'Создан каталог для резервного копирования.',
  'Starting the database backup process...' => 'Запуск процесса резервного копирования базы данных...',
  'Database backed up successfully!' => 'База данных успешно сохранена!',
  'Starting the file system backup process...' => 'Запуск процесса резервного копирования файловой системы...',
  'File system backed up successfully!' => 'Файловая система успешно сохранена!',
  'Starting to pack the backup...' => 'Начинаем упаковывать резервную копию...',
  'Done packing the backup!' => 'Закончена упаковка бэкапа!',
  'Backup complete!' => 'Резервное копирование завершено!',
);
