<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "ext_ip_location_maxmind" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link https://www.mailwizz.com/
 * @copyright 2013-2018 MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'MaxMind.com' => 'MaxMind.com',
  'Offers IP location based on GeoLite2 database created by MaxMind' => 'Offers IP location based on GeoLite2 database created by MaxMind',
  'Ip location service from MaxMind.com' => 'Ip location service from MaxMind.com',
  'Status on email open' => 'Status on email open',
  'Status on track url' => 'Status on track url',
  'Status on unsubscribe' => 'Status on unsubscribe',
  'Status on customer login' => 'Status on customer login',
  'Sort order' => 'Sort order',
  'Whether this service is enabled and can be used' => 'Whether this service is enabled and can be used',
  'Whether to collect ip location information when a campaign email is opened' => 'Whether to collect ip location information when a campaign email is opened',
  'Whether to collect ip location information when a campaign link is clicked and tracked' => 'Whether to collect ip location information when a campaign link is clicked and tracked',
  'Whether to collect ip location information when a subscriber unsubscribes via a campaign' => 'Whether to collect ip location information when a subscriber unsubscribes via a campaign',
  'Whether to collect ip location information when a customer logs in' => 'Whether to collect ip location information when a customer logs in',
  'If multiple location services active, sort order decides which one queries first' => 'If multiple location services active, sort order decides which one queries first',
  'This product includes GeoLite2 data created by MaxMind, available from {from}' => 'This product includes GeoLite2 data created by MaxMind, available from {from}',
);
