<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "list_pages" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link https://www.mailwizz.com/
 * @copyright 2013-2018 MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'List' => 'List',
  'Type' => 'Type',
  'Content' => 'Content',
  'The following tag is required but was not found in your content: {tag}' => 'The following tag is required but was not found in your content: {tag}',
  'Your unsubscribe form url is:' => 'Your unsubscribe form url is:',
  'Preview it now!' => 'Preview it now!',
  'Select another list page to edit' => 'Select another list page to edit',
  'Your subscribe form url is:' => 'Your subscribe form url is:',
  'Pages' => 'Страницы',
  'List pages' => 'Список страниц',
  'Subscribe form' => 'Subscribe form',
  'Pending subscribe' => 'Pending subscribe',
  'Subscription confirmed' => 'Subscription confirmed',
  'Update Profile' => 'Update Profile',
  'Unsubscribe form' => 'Unsubscribe form',
  'Unsubscribe confirmation' => 'Unsubscribe confirmation',
  'Subscribe confirm email' => 'Subscribe confirm email',
  'Unsubscribe confirm email' => 'Unsubscribe confirm email',
  'Welcome email' => 'Welcome email',
  'Subscription confirmed approval' => 'Subscription confirmed approval',
  'Subscription confirmed approval email' => 'Subscription confirmed approval email',
  'Email subject' => 'Email subject',
);
