<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "list_page_types" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link https://www.mailwizz.com/
 * @copyright 2013-2018 MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Available tags:' => 'Available tags:',
  'List page types' => 'List page types',
  'Update page type' => 'Update page type',
  'Type' => 'Type',
  'Name' => 'Name',
  'Description' => 'Description',
  'Default content' => 'Default content',
  'Full html' => 'Full html',
  'Email subject' => 'Email subject',
  'Please note, these pages are the base pages shown in customers area for each list.<br /> The customer has the ability to modify them to fit their needs for any particular list.' => 'Please note, these pages are the base pages shown in customers area for each list.<br /> The customer has the ability to modify them to fit their needs for any particular list.',
);
