<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "list_subscriber" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link https://www.mailwizz.com/
 * @copyright 2013-2018 MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Update subscriber' => 'Редактировать подписчика',
  'View' => 'View',
  'Export' => 'Export',
  'Create list' => 'Create list',
  'Confirm' => 'Confirm',
  'Disable' => 'Disable',
  'Unsubscribe' => 'Unsubscribe',
  'Blacklist' => 'Blacklist',
  'Delete' => 'Delete',
);
