<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "sending_domains" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'This domain has been verified' => 'Этот домен был подтвержден',
  'Verify this domain' => 'Подтвердите этот домен',
  'Please edit your DNS records for {domain} domain and add the following TXT record: ' => 'Отредактируйте записи DNS для домена {domain} и добавьте следующую TXT запись: ',
  'For best delivery rates, your domain SPF record must look like:' => 'Для получения наилучших показателей доставки, запись SPF вашего домена должна выглядеть следующим образом:',
  'After you have added the DNS records for your domain, please click the Verify DNS records button below to verify your domain.' => 'После того, как вы добавили записи DNS для своего домена, нажмите кнопку «Проверить записи DNS» ниже, чтобы подтвердить свой домен.',
  'Please note that it can take up to 48 hours for DNS changes to propagate. If verification fails now, please try again later.' => 'Обратите внимание, что распространение DNS может занять до 48 часов. Если проверка не удалась сейчас, повторите попытку позже.',
  'Verify DNS records' => 'Проверить записи DNS',
  'Customer' => 'Пользователь',
  'Sending domains' => 'Домены отправки',
  'With sending domains you can verify the authenticity of the domain used in the campaigns FROM email field.' => 'With sending domains you can verify the authenticity of the domain used in the campaigns FROM email field.',
  'Verification is very simple, it involves adding just two DNS TXT records for the domain used in the FROM field of a campaign.' => 'Verification is very simple, it involves adding just two DNS TXT records for the domain used in the FROM field of a campaign.',
  'Once a sending domain is verified, all future campaigns sent from the verified domain will be DKIM signed and will pass SPF validation, thus giving a higher inbox delivery rate.' => 'Once a sending domain is verified, all future campaigns sent from the verified domain will be DKIM signed and will pass SPF validation, thus giving a higher inbox delivery rate.',
  'Your system misses a few PHP functions/extensions in order to use this feature.' => 'Your system misses a few PHP functions/extensions in order to use this feature.',
  'View sending domains' => 'Просмотрт доменов отправки',
  'Create new sending domain' => 'Создать новый домен отправки',
  'Update sending domain' => 'Обновить домен отправки',
  'Unable to retrieve the TXT records for your domain name.' => 'Невозможно получить записи TXT для вашего доменного имени.',
  'Unable to find proper TXT record for your domain name, if you just added the records please wait for them to propagate.' => 'Невозможно найти правильную запись TXT для вашего доменного имени, если вы только что добавили записи, пожалуйста, подождите, пока они распространятся.',
  'Your domain has been successfully verified.' => 'Ваш домен был успешно подтвержден.',
  'Domain' => 'Domain',
  'Domain name' => 'Имя домена',
  'Dkim private key' => 'Dkim закрытый ключ',
  'Dkim public key' => 'Dkim публичный ключ',
  'Locked' => 'Заблокировать',
  'Verified' => 'Подтвержден',
  'DKIM Signing' => 'DKIM Подпись',
  'If this domain is verified in behalf of a customer, choose the customer.' => 'Если этот домен подтвержден от имени клиента, выберите клиента.',
  'Domain name, i.e: example.com' => 'Имя домена, например: example.com',
  'Set this to yes only if you already have DNS records set for this domain.' => 'Установите значение «Да» только в том случае, если для этого домена уже установлены записи DNS.',
  'Whether this domain is locked and the customer cannot modify or delete it.' => 'Является ли этот домен заблокированным, и клиент не может изменить или удалить его.',
  'Whether we should use DKIM to sign outgoing campaigns for this domain.' => 'Должны ли мы использовать DKIM для подписи исходящих кампаний для этого домена.',
  'DKIM private key, leave this empty to be auto-generated. Please do not edit this record unless you really know what you are doing.' => 'DKIM закрытый ключ, оставьте это поле пустым для автоматической генерации. Пожалуйста, не редактируйте эту запись, если вы действительно не знаете, что делаете.',
  'DKIM public key, leave this empty to be auto-generated. Please do not edit this record unless you really know what you are doing.' => 'DKIM открытый ключ, оставьте это поле пустым для автоматической генерации. Пожалуйста, не редактируйте эту запись, если вы действительно не знаете, что делаете.',
  'OpenSSL extension missing.' => 'OpenSSL extension missing.',
  '{func} function must be enabled in order to handle the DKIM keys.' => '{func} function must be enabled in order to handle the DKIM keys.',
  'Unable to create {dir} directory.' => 'Unable to create {dir} directory.',
  'While generating the private key, exec failed with: {fail}' => 'While generating the private key, exec failed with: {fail}',
  'Unknown error, most probably cannot exec the openssl command!' => 'Unknown error, most probably cannot exec the openssl command!',
  'Unable to check the private key file.' => 'Unable to check the private key file.',
  'While generating the public key, exec failed with: {fail}' => 'While generating the public key, exec failed with: {fail}',
  'Unable to check the public key file.' => 'Unable to check the public key file.',
  'You have reached the maximum number of allowed sending domains!' => 'You have reached the maximum number of allowed sending domains!',
);
