<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "templates" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link https://www.mailwizz.com/
 * @copyright 2013-2018 MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Recipient(s)' => 'Recipient(s)',
  'i.e: a@domain.com, b@domain.com, c@domain.com' => 'i.e: a@domain.com, b@domain.com, c@domain.com',
  'From email (optional)' => 'From email (optional)',
  'i.e: me@domain.com' => 'i.e: me@domain.com',
  'Subject' => 'Subject',
  '[TEST TEMPLATE] {name}' => '[TEST TEMPLATE] {name}',
);
