<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "users" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link https://www.mailwizz.com/
 * @copyright 2013-2018 MailWizz EMA (https://www.mailwizz.com)
 * @license https://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Users' => 'Пользователи',
  'Update your account data.' => 'Обновление ваших пользовательских данных.',
  'Go to login' => 'Перейти к логину',
  'Sign in to start your session' => 'Войдите, чтобы начать сеанс',
  'Forgot password?' => 'Забыли пароль?',
  'Please follow the following url in order to reset your password:' => 'Пройдите по следующей ссылке, чтобы сбросить пароль:',
  'If for some reason you cannot click the above url, please paste this one into your browser address bar:' => 'Если по какой-либо причине Вы не сможете кликнуть по указанному URL, вставьте его в адресную строку браузера:',
  'Your new login is:' => 'Ваш новый логин:',
  'Email' => 'Email',
  'Password' => 'Пароль',
  'You can login by clicking <a href="{loginUrl}">here</a>.' => 'Вы можете войти кликнув <a href="{loginUrl}">здесь</a>.',
  'If for some reason the link doesn\'t work, please copy the following url into your browser address bar:' => 'Если по какой-либо причине линк не работает, скопируйте его в адресную строку Вашего браузера:',
  'Remember me' => 'Запомнить меня',
  'Unable to login with the given identity!' => 'Не удалось войти с данным идентификатором!',
  'Update user group' => 'Обновоить группу пользователей',
  'View users' => 'Просмотр пользователей',
  'Create new user' => 'Создать нового пользователя',
  'You are not allowed to update the master administrator!' => 'Вам запрещено обновлять администратора системы!',
  'Update user' => 'Обновить пользователя',
  'Please login' => 'Пожалуйста залогиньтесь',
  'Password reset request!' => 'Запрос сброса пароля!',
  'Retrieve a new password for your account.' => 'Получить новый пароль для своей учетной записи.',
  'Update account' => 'Обновить аккаунт',
  'Invalid login credentials.' => 'Неверные логин или пароль.',
  'Request' => 'Запрос',
  'User' => 'Пользователь',
  'Reset key' => 'Сброс ключа',
  'Ip address' => 'Ip адрес',
  'Token' => 'Токен',
  'Language' => 'Язык',
  'Group' => 'Группа',
  'First name' => 'Имя',
  'Last name' => 'Фамилия',
  'Timezone' => 'Временная зона',
  'Avatar' => 'Аватар',
  'New avatar' => 'Новый аватар',
  'Removable' => 'Удаляемый',
  'Confirm email' => 'Подтвердить Email',
  'Confirm password' => 'Подтвердить пароль',
  'The avatars storage directory({path}) does not exists and cannot be created!' => 'Каталог для сохранения аватаров({path}) не существует и не может быть создан!',
  'Cannot move the avatar into the correct storage folder!' => 'Не могу переместить аватар в правильный каталог!',
  'You are impersonating the customer {customerName}.' => 'Вы выдаете себя за пользователя {customerName}.',
  'Please click {linkBack} to logout in order to finish impersonating.' => 'Пожалуйста нажмите {linkBack} для выхода из системы.',
  '2FA enabled' => '2FA enabled',
  '2FA code' => '2FA code',
  'Please make sure you scan the QR code in your authenticator application before enabling this feature, otherwise you will be locked out from your account' => 'Please make sure you scan the QR code in your authenticator application before enabling this feature, otherwise you will be locked out from your account',
);
