<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "user_groups" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package MailWizz EMA
 * @author Serban George Cristian <cristian.serban@mailwizz.com> 
 * @link http://www.mailwizz.com/
 * @copyright 2013-2017 MailWizz EMA (http://www.mailwizz.com)
 * @license http://www.mailwizz.com/license/
 * @since 1.1
 */
 
 return array (
  'Access' => 'Доступ',
  'Allow all' => 'Разрешить все',
  'Deny all' => 'Запретить все',
  'View user groups' => 'Просмотр групп пользователей',
  'User groups' => 'Группы пользователей',
  'Create new user group' => 'Создать новую группу пользователей',
  'You do not have the permission to access this resource!' => 'У Вас нет доступа к этому ресурсу!',
  'Group' => 'Группа',
  'Name' => 'Имя',
  'Users count' => 'Количество',
  'Route' => 'Route',
  'Description' => 'Описание',
  'Controller' => 'Controller',
  'Action' => 'Действие',
);
